name: Publish
on:
    issues:
        types:
            - labeled

jobs:
    label-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                    node-version: '20'

            - name: Run NodeJS
              run: node .github/workflows/publish.js ${{ github.event.label.name }}